### ISSUE TITLE
It is now the year 2020, when will Youtube Lazy Load be updated to be compatible with the latest version of Pale Moon browser?

### ISSUE THREAD

**Issue by PMUserCA** [JustOff/youtube-lazy-load#6] opened 2020-03-03 07:03 UTC
It is now the year 2020.  When will Youtube Lazy Load be updated to be compatible with the latest version of Pale Moon browser?  Is this extension dead now?  If not, then please update it to be compatible with the newest version of Pale Moon.  Thank you.

**Comment by JustOff** [comment] 2020-03-03 07:06
Duplicate of #3.

**Closed as completed by JustOff** 2020-03-03 07:06 UTC
